### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by araichev** [davisp/ghp-import#58]
Using Python 3.5.2 and ghp-import version 0.5, running ``ghp-import _build/singlehtml/`` gives me the following error.

```
  File "/Users/bingo/.virtualenvs/vegehead/bin/ghp-import", line 11, in <module>
    sys.exit(main())
  File "/Users/bingo/.virtualenvs/vegehead/lib/python3.5/site-packages/ghp_import.py", line 192, in main
    check_repo(parser)
  File "/Users/bingo/.virtualenvs/vegehead/lib/python3.5/site-packages/ghp_import.py", line 65, in check_repo
    error = error.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by araichev** [comment]
Aha, but it works under Python 2.7.5.  So i guess the problem here is that your package is not compatible with Python 3.5.2 and maybe even Python 3.*.  It would be good to note that in the project README.

**Comment by araichev** [comment]
I discovered ghp-import2 (https://github.com/ionelmc/python-ghp-import), which works on Python 3.5.2 and which i am now using.

**Comment by marco-c** [comment]
Version 0.4.1 used to work for me, so it's a new regression.

**Comment by davisp** [comment]
Yeah, I screwed up by not checking a commit for Windows compatibility. I've published 0.5.1 which should fix the issue.

**Comment by davisp** [comment]
Actually, this is fixed in 0.5.2 because I didn't read close enough and thought it was a duplicate of #57. This should theoretically be fixed now. Whenever default Python interpreters move over to 3.x I'll probably not screw 3.x string issues up as much (but then will probably start screwing them up for 2.x interpreters...)
